# version of the readthedocs config syntax, NOT the version of my package
version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  version: 3.8
  install:
    # give RTD a DIFFERENT requirements file than the users, since users don't care about having Sphinx/Jinja/etc. for using flexpy
    - requirements: rtd_requirements.txt
