from flexpy.Rt import Rt
from flexpy.FlexPyUtil import get_child_object

class RtLangProject(Rt):
    def __init__(self, el, tag_dict):
        super().__init__(el, tag_dict)
        self.el = el
        self.tag_dict = tag_dict
        self.AffixCategories = get_child_object(self.el, "AffixCategories", self.tag_dict)
        self.AnalysisWss = get_child_object(self.el, "AnalysisWss", self.tag_dict)
        self.AnalyzingAgents = get_child_object(self.el, "AnalyzingAgents", self.tag_dict)
        self.AnnotationDefs = get_child_object(self.el, "AnnotationDefs", self.tag_dict)
        self.Annotations = get_child_object(self.el, "Annotations", self.tag_dict)
        self.AnthroList = get_child_object(self.el, "AnthroList", self.tag_dict)
        self.ConfidenceLevels = get_child_object(self.el, "ConfidenceLevels", self.tag_dict)
        self.CurAnalysisWss = get_child_object(self.el, "CurAnalysisWss", self.tag_dict)
        self.CurPronunWss = get_child_object(self.el, "CurPronunWss", self.tag_dict)
        self.CurVernWss = get_child_object(self.el, "CurVernWss", self.tag_dict)
        self.DateCreated = get_child_object(self.el, "DateCreated", self.tag_dict)
        self.DateModified = get_child_object(self.el, "DateModified", self.tag_dict)
        self.DiscourseData = get_child_object(self.el, "DiscourseData", self.tag_dict)
        self.Education = get_child_object(self.el, "Education", self.tag_dict)
        self.FilePathsInTsStrings = get_child_object(self.el, "FilePathsInTsStrings", self.tag_dict)
        self.Filters = get_child_object(self.el, "Filters", self.tag_dict)
        self.GenreList = get_child_object(self.el, "GenreList", self.tag_dict)
        self.HomographWs = get_child_object(self.el, "HomographWs", self.tag_dict)
        self.LexDb = get_child_object(self.el, "LexDb", self.tag_dict)
        self.Locations = get_child_object(self.el, "Locations", self.tag_dict)
        self.MorphologicalData = get_child_object(self.el, "MorphologicalData", self.tag_dict)
        self.MsFeatureSystem = get_child_object(self.el, "MsFeatureSystem", self.tag_dict)
        self.Overlays = get_child_object(self.el, "Overlays", self.tag_dict)
        self.PartsOfSpeech = get_child_object(self.el, "PartsOfSpeech", self.tag_dict)
        self.People = get_child_object(self.el, "People", self.tag_dict)
        self.PhFeatureSystem = get_child_object(self.el, "PhFeatureSystem", self.tag_dict)
        self.PhonologicalData = get_child_object(self.el, "PhonologicalData", self.tag_dict)
        self.Positions = get_child_object(self.el, "Positions", self.tag_dict)
        self.ResearchNotebook = get_child_object(self.el, "ResearchNotebook", self.tag_dict)
        self.Restrictions = get_child_object(self.el, "Restrictions", self.tag_dict)
        self.Roles = get_child_object(self.el, "Roles", self.tag_dict)
        self.SemanticDomainList = get_child_object(self.el, "SemanticDomainList", self.tag_dict)
        self.Status = get_child_object(self.el, "Status", self.tag_dict)
        self.Styles = get_child_object(self.el, "Styles", self.tag_dict)
        self.TextMarkupTags = get_child_object(self.el, "TextMarkupTags", self.tag_dict)
        self.TimeOfDay = get_child_object(self.el, "TimeOfDay", self.tag_dict)
        self.TranslatedScripture = get_child_object(self.el, "TranslatedScripture", self.tag_dict)
        self.TranslationTags = get_child_object(self.el, "TranslationTags", self.tag_dict)
        self.VernWss = get_child_object(self.el, "VernWss", self.tag_dict)
