from flexpy.Rt import Rt
from flexpy.FlexPyUtil import get_child_object

class RtLangProject(Rt):
    def __init__(self, rt, tag_dict):
        super().__init__(rt, tag_dict)
        self.AffixCategories = get_child_object(self.rt, "AffixCategories", self.tag_dict)
        self.AnalysisWss = get_child_object(self.rt, "AnalysisWss", self.tag_dict)
        self.AnalyzingAgents = get_child_object(self.rt, "AnalyzingAgents", self.tag_dict)
        self.AnnotationDefs = get_child_object(self.rt, "AnnotationDefs", self.tag_dict)
        self.Annotations = get_child_object(self.rt, "Annotations", self.tag_dict)
        self.AnthroList = get_child_object(self.rt, "AnthroList", self.tag_dict)
        self.ConfidenceLevels = get_child_object(self.rt, "ConfidenceLevels", self.tag_dict)
        self.CurAnalysisWss = get_child_object(self.rt, "CurAnalysisWss", self.tag_dict)
        self.CurPronunWss = get_child_object(self.rt, "CurPronunWss", self.tag_dict)
        self.CurVernWss = get_child_object(self.rt, "CurVernWss", self.tag_dict)
        self.DateCreated = get_child_object(self.rt, "DateCreated", self.tag_dict)
        self.DateModified = get_child_object(self.rt, "DateModified", self.tag_dict)
        self.DiscourseData = get_child_object(self.rt, "DiscourseData", self.tag_dict)
        self.Education = get_child_object(self.rt, "Education", self.tag_dict)
        self.FilePathsInTsStrings = get_child_object(self.rt, "FilePathsInTsStrings", self.tag_dict)
        self.Filters = get_child_object(self.rt, "Filters", self.tag_dict)
        self.GenreList = get_child_object(self.rt, "GenreList", self.tag_dict)
        self.HomographWs = get_child_object(self.rt, "HomographWs", self.tag_dict)
        self.LexDb = get_child_object(self.rt, "LexDb", self.tag_dict)
        self.Locations = get_child_object(self.rt, "Locations", self.tag_dict)
        self.MorphologicalData = get_child_object(self.rt, "MorphologicalData", self.tag_dict)
        self.MsFeatureSystem = get_child_object(self.rt, "MsFeatureSystem", self.tag_dict)
        self.Overlays = get_child_object(self.rt, "Overlays", self.tag_dict)
        self.PartsOfSpeech = get_child_object(self.rt, "PartsOfSpeech", self.tag_dict)
        self.People = get_child_object(self.rt, "People", self.tag_dict)
        self.PhFeatureSystem = get_child_object(self.rt, "PhFeatureSystem", self.tag_dict)
        self.PhonologicalData = get_child_object(self.rt, "PhonologicalData", self.tag_dict)
        self.Positions = get_child_object(self.rt, "Positions", self.tag_dict)
        self.ResearchNotebook = get_child_object(self.rt, "ResearchNotebook", self.tag_dict)
        self.Restrictions = get_child_object(self.rt, "Restrictions", self.tag_dict)
        self.Roles = get_child_object(self.rt, "Roles", self.tag_dict)
        self.SemanticDomainList = get_child_object(self.rt, "SemanticDomainList", self.tag_dict)
        self.Status = get_child_object(self.rt, "Status", self.tag_dict)
        self.Styles = get_child_object(self.rt, "Styles", self.tag_dict)
        self.TextMarkupTags = get_child_object(self.rt, "TextMarkupTags", self.tag_dict)
        self.TimeOfDay = get_child_object(self.rt, "TimeOfDay", self.tag_dict)
        self.TranslatedScripture = get_child_object(self.rt, "TranslatedScripture", self.tag_dict)
        self.TranslationTags = get_child_object(self.rt, "TranslationTags", self.tag_dict)
        self.VernWss = get_child_object(self.rt, "VernWss", self.tag_dict)
